name: amidehayimanot_zimare
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.10.0
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  scrollable_positioned_list: ^0.3.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  
  # This is the correct location for this package
  change_app_package_name: ^1.1.0

# This section is ONLY for configuring the launcher icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
   - assets/images/